version: '3'

services:
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - 8081:80
    depends_on:
      - tetris-app
    environment:
      - UWSGI_HOST=${UWSGI_HOST}
      - UWSGI_PORT=${UWSGI_PORT}
      - APP_HOST=${APP_HOST}
      - APP_PORT=${APP_PORT}
  tetris-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080