version: '3'

services:
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - 8081:80
    depends_on:
      - tetris-app
    environment:
      - UWSGI_HOST=tetris-app
      - UWSGI_PORT=8080
      - APP_HOST='0.0.0.0'
      - APP_PORT=8080
  tetris-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080