apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "my-application.fullname" . }}
  labels:
    {{- include "my-application.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "my-application.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "my-application.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Values.appImage.name }}
          image: "{{ .Values.appImage.repository }}:{{ .Values.appImage.tag }}"
          imagePullPolicy: {{ .Values.appImage.pullPolicy }}
          ports:
            - containerPort: {{ .Values.appImage.containerPort }}
          env:
            {{- toYaml .Values.appImage.env | nindent 12}}
          resources:
            {{- toYaml .Values.appImage.resources | nindent 12 }}
        - name: {{ .Values.nginxImage.name }}
          image: "{{ .Values.nginxImage.repository }}:{{ .Values.nginxImage.tag }}"
          imagePullPolicy: {{ .Values.nginxImage.pullPolicy }}
          ports:
            - containerPort: {{ .Values.nginxImage.containerPort }}
          env:
            {{- toYaml .Values.nginxImage.env | nindent 12}}
          resources:
            {{- toYaml .Values.nginxImage.resources | nindent 12 }}
