apiVersion: v1
kind: Service
metadata:
  name: {{ include "my-application.fullname" . }}
  labels:
    {{- include "my-application.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.nginxImage.containerPort }}
  selector:
    {{- include "my-application.selectorLabels" . | nindent 4 }}
