name: Docker Image CI

on:
  push:
    branches: [ "ws_challenge" ]
  pull_request:
    branches: [ "ws_challenge" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Docker Buildx
      run: pwd
    - name: Build the Docker image
      run: cd scripts && chmod +x buildAndPush.sh
    - name: verify the path
      run: ls -la
    - name: Push the Docker image  
      run: ./buildAndPush.sh
