name: Docker Image CI

on:
  push:
    branches: [ "ws_challenge" ]
  pull_request:
    branches: [ "ws_challenge" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push ${{env.APP_NAME}} Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ${{secrets.REGISTRY}}/${{env.APP_NAME}}:latest,
            ${{secrets.REGISTRY}}/${{env.APP_NAME}}:${{ github.sha }}
          no-cache: true
          platforms: linux/amd64,linux/arm64
      -
        name: Build and push ${{env.NGINX_NAME}} Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./nginx/
          push: true
          tags: |
            ${{secrets.REGISTRY}}/${{env.NGINX_NAME}}:latest,
            ${{secrets.REGISTRY}}/${{env.NGINX_NAME}}:${{ github.sha }}
          no-cache: true
          platforms: linux/amd64,linux/arm64
